terms:
  - id: administrator
    term: Administrator
  - id: author
    term: Author
  - id: contactPerson
    term: Contact person
  - id: dataAnalyser
    term: Data analyser
  - id: dataCollector
    term: Data collector
  - id: dataCreator
    term: Data creator
  - id: dataManager
    term: Data manager
  - id: depositingUser
    term: Depositing user
  - id: editor
    term: Editor
  - id: investigator
    term: Investigator
  - id: producer
    term: Producer
  - id: projectLeader
    term: Project leader
  - id: publisher
    term: Publisher
  - id: projectMember
    term: Project member
  - id: relatedPerson
    term: Related person
  - id: researcher
    term: Researcher
  - id: researcherGroup
    term: Researcher group
  - id: rightsHolder
    term: Rights holder
  - id: sponsor
    term: Sponsor
  - id: supervisor
    term: Supervisor
  - id: other
    term: Other