terms:
  - id: funder
    term: Funder
  - id: hostingInstitution
    term: Hosting Institution
  - id: rightsHolder
    term: Rights Holder
  - id: sponsor
    term: Sponsor
  - id: publisher
    term: Publisher
  - id: registrationAgency
    term: Registration Agency
  - id: registrationAuthority
    term: Registration Authority
  - id: distributor
    term: Distributor
  - id: advocacy
    term: Advocacy
  - id: author
    term: Author
