terms:
  - id: cites
    term: Cites
  - id: isCitedBy
    term: Is Cited By
  - id: isSupplementTo
    term: Is Supplement To
  - id: isSupplementedBy
    term: Is Supplemented By
  - id: continues
    term: Continues
  - id: isContinuedBy
    term: Is Continued By
  - id: hasMetadata
    term: Has Metadata
  - id: isMetadataFor
    term: Is Metadata For
  - id: isNewVersionOf
    term: Is New Version Of
  - id: isPreviousVersionOf
    term: Is Previous Version Of
  - id: isPartOf
    term: Is Part Of
  - id: hasPart
    term: Has Part
  - id: isReferencedBy
    term: Is Referenced By
  - id: references
    term: References
  - id: isDocumentedBy
    term: Is Documented By
  - id: documents
    term: Documents
  - id: isCompiledBy
    term: Is Compiled By
  - id: compiles
    term: Compiles
  - id: isVariantFormOf
    term: Is Variant Form Of
  - id: isOriginalFormOf
    term: Is Original Form Of
  - id: isIdenticalTo
    term: Is Identical To
  - id: isReviewedBy
    term: Is Reviewed By
  - id: reviews
    term: Reviews
  - id: isDerivedFrom
    term: Is Derived From
  - id: isSourceOf
    term: Is Source Of
  - id: isCommentOn
    term: Is Comment On
  - id: hasComment
    term: Has Comment
  - id: isReplyTo
    term: Is Reply To
  - id: hasReply
    term: Has Reply
  - id: basedOnData
    term: Based On Data
  - id: hasRelatedMaterial
    term: Has Related Material
  - id: isBasedOn
    term: Is Based On
  - id: isBasisFor
    term: Is Basis For
  - id: requires
    term: Requires
  - id: isRequiredBy
    term: Is Required By
  - id: hasParent
    term: Has Parent
  - id: isParentOf
    term: Is Parent Of
