terms:
  - id: artDesignItem
    term: Art Design Item
  - id: article
    term: Article
  - id: audio
    term: Audio
  - id: book
    term: Book
  - id: bookSection
    term: Book Section
  - id: conferenceWorkshopItem
    term: Conference Workshop Item
  - id: dataset
    term: Dataset
  - id: examPaper
    term: Exam Paper
  - id: image
    term: Image
  - id: journal
    term: Journal
  - id: learningObject
    term: Learning Object
  - id: movingImage
    term: Moving Image
  - id: musicComposition
    term: Music Composition
  - id: other
    term: Other
  - id: patent
    term: Patent
  - id: performance
    term: Performance
  - id: preprint
    term: Preprint
  - id: report
    term: Report
  - id: review
    term: Review
  - id: showExhibition
    term: Show Exhibition
  - id: software
    term: Software
  - id: text
    term: Text
  - id: thesisDissertation
    term: Thesis Dissertation
  - id: unkown
    term: Unkown
  - id: website
    term: Website
  - id: workflow
    term: Workflow
  - id: equipment
    term: Equipment