language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

before_install:
  - bash -c "yes | gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.0@global rake"
  - gem update --system
  - cd willow

env:
  - RAILS_ENV=test 
    SECRET_KEY_BASE_TEST=secret 
    SAMVERA_INTERNAL_HOST=http://repository.your-institution.ac.uk
