version: '3.1'

# these are the DEVELOPMENT overrides to docker-compose.yml

services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  solr:
    ports:
      - "8983:8983"

  fedora:
    ports:
      - "8080:8080"
    restart: "no"

  willow:
    build:
      args:
        - RAILS_ENV=development
    env_file:
      - .env.development
    environment:
      # these AWS credentials *MUST* be present but *MUST NOT* be valid!
      - AWS_ACCESS_KEY_ID=ignored
      - AWS_SECRET_ACCESS_KEY=ignored
    volumes:
      - ./willow:/willow.development
      - ./willow_sword:/willow_sword # necessary for running wilow_sword locally. NB: it must be named "/willow_sword".
      - ./.git:/.git                 # necessary for running wilow_sword locally
      - ./willow/seed:/seed:ro       # mount the seed directory so it can be used to load local seed data
    restart: "no"

#  geoblacklight:
#    build:
#      args:
#        - RAILS_ENV=development
#    env_file:
#      - .env.development
#    volumes:
#      - ./geoblacklight:/geoblacklight.development
#    restart: "no"

  #kinesalite:
    #ports:
    #  - "4567:4567"

# Local shibboleth configs

  sp:
    build: ./sp/
    networks:
     - back
     - front
    secrets:
     - source: sp_key
  httpd-proxy:
    build: ./httpd-proxy/
    networks:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"
  idp:
    build: ./idp/
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer
  ldap:
    build: ./ldap/
    networks:
      - back

    secrets:
      idp_backchannel:
        file: ./secrets/idp/idp-backchannel.p12
      idp_browser:
        file: ./secrets/idp/idp-browser.p12
      idp_encryption:
        file: ./secrets/idp/idp-encryption.key
      idp_signing:
        file: ./secrets/idp/idp-signing.key
      idp_sealer:
        file: ./secrets/idp/sealer.jks
      ssp_key:
        file: ./secrets/simplesamlphp/server.pem
      sp_key:
        file: ./secrets/sp/sp-key.pem

    networks:
      front:
        driver: bridge
      back:
        driver: bridge
