---
2.0.0: &latest
  create_and_update: &create_and_update
    # NOTE: This document actually directly controls how the message is generated. Adding a new or removing an item needs
    # to be done in conjunction with the attribute rendering endpoint. So for example, if you were to add a new
    # objectWiggler in here, you would probably need to have a file in app/models/cdm/messaging called object_wibble.rb
    # defining the class ObjectWibble < MessageMapper and exposing a value method to return what the value you would
    # want the passed in object (the model instance) to expose in the message.
    objectUuid:
    objectTitle:
    objectPersonRole:
    - person:
        personUuid:
        personIdentifier:
        - personIdentifierValue:
          personIdentifierType:
        personEntitlement:
        -
        personAffiliation:
        -
        personGivenName:
        personCn:
        personSn:
        personTelephoneNumber:
        personMail:
        personOrganisationUnit:
          organisationUnitUuid:
          organisationUnitName:
          organisation:
            organisationJiscId:
            organisationName:
            organisationType:
            organisationAddress:
      role:
    objectDescription:
    objectRights:
    - rightsStatement:
      -
      rightsHolder:
      -
      licence:
      - licenceName:
        licenceIdentifier:
      access:
      - accessType:
        accessStatement:
    objectDate:
    - dateValue:
      dateType:
    objectKeywords:
    -
    objectCategory:
    -
    objectResourceType:
    objectValue:
    objectIdentifier:
    - identifierValue:
      identifierType:
    objectRelatedIdentifier:
    - identifierValue:
      identifierType:
      relationType:
    objectOrganisationRole:
    - organisation:
        organisationJiscId:
        organisationName:
        organisationType:
        organisationAddress:
      role:
    objectFile:
    - fileUuid:
      fileIdentifier:
      fileName:
      fileSize:
      fileLabel:
      fileDateCreated:
        dateValue:
        dateType:
#      fileRights:
#        rightsStatement:
#        -
#        rightsHolder:
#        -
#        licence:
#        - licenceName:
#          licenceIdentifier:
#        access:
#        - accessType:
#          accessStatement:
      fileChecksum:
      - checksumUuid:
        checksumType:
        checksumValue:
      fileFormatType:
      fileCompositionLevel:
      fileHasMimeType:
      fileDateModified:
      - dateValue:
        dateType:
#      filePuid:
#      -
      fileUse:
      filePreservationEvent:
      - preservationEventValue:
        preservationEventType:
        preservationEventDetail:
      fileUploadStatus:
      fileStorageStatus:
      fileLastDownloaded:
        dateValue:
        dateType:
#      fileTechnicalAttributes:
#      -
      fileStorageLocation:
      fileStoragePlatform:
        storagePlatformUuid:
        storagePlatformName:
        storagePlatformType:
        storagePlatformCost:
    #objectPreservationEvent:
    #- preservationEventValue:
    #  preservationEventType:
    #  preservationEventDetail:
  create:
    <<: *create_and_update
  read:
    objectUuid:
  update:
    <<: *create_and_update
  delete:
    objectUuid:
current:
  <<: *latest
